export const arrayJSON = [
  {
    exampleCode: "../MDNExamples/js-examples/array/array-at.js",
    fileName: "array-at.html",
    title: "JavaScript Demo: Array.at()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-concat.js",
    fileName: "array-concat.html",
    title: "JavaScript Demo: Array.concat()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-copywithin.js",
    fileName: "array-copywithin.html",
    title: "JavaScript Demo: Array.copyWithin()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-entries.js",
    fileName: "array-entries.html",
    title: "JavaScript Demo: Array.entries()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-every.js",
    fileName: "array-every.html",
    title: "JavaScript Demo: Array.every()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-fill.js",
    fileName: "array-fill.html",
    title: "JavaScript Demo: Array.fill()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-filter.js",
    fileName: "array-filter.html",
    title: "JavaScript Demo: Array.filter()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-find.js",
    fileName: "array-find.html",
    title: "JavaScript Demo: Array.find()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-findlast.js",
    fileName: "array-findlast.html",
    title: "JavaScript Demo: Array.findLast()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-findindex.js",
    fileName: "array-findindex.html",
    title: "JavaScript Demo: Array.findIndex()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-findlastindex.js",
    fileName: "array-findlastindex.html",
    title: "JavaScript Demo: Array.findLastIndex()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-flat.js",
    fileName: "array-flat.html",
    title: "JavaScript Demo: Array.flat()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-flatmap.js",
    fileName: "array-flatmap.html",
    title: "JavaScript Demo: Array.flatMap()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-foreach.js",
    fileName: "array-foreach.html",
    title: "JavaScript Demo: Array.forEach()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-from.js",
    fileName: "array-from.html",
    title: "JavaScript Demo: Array.from()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-groupby.js",
    fileName: "array-groupby.html",
    title: "JavaScript Demo: Array.groupBy()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-includes.js",
    fileName: "array-includes.html",
    title: "JavaScript Demo: Array.includes()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-indexof.js",
    fileName: "array-indexof.html",
    title: "JavaScript Demo: Array.indexOf()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-iterator.js",
    fileName: "array-iterator.html",
    title: "JavaScript Demo: Array.prototype[@@iterator]()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-join.js",
    fileName: "array-join.html",
    title: "JavaScript Demo: Array.join()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-keys.js",
    fileName: "array-keys.html",
    title: "JavaScript Demo: Array.keys()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-lastindexof.js",
    fileName: "array-lastindexof.html",
    title: "JavaScript Demo: Array.lastIndexOf()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-length.js",
    fileName: "array-length.html",
    title: "JavaScript Demo: Array.length",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-map.js",
    fileName: "array-map.html",
    title: "JavaScript Demo: Array.map()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-push.js",
    fileName: "array-push.html",
    title: "JavaScript Demo: Array.push()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-pop.js",
    fileName: "array-pop.html",
    title: "JavaScript Demo: Array.pop()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-reduce-right.js",
    fileName: "array-reduce-right.html",
    title: "JavaScript Demo: Array.reduceRight()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-reduce.js",
    fileName: "array-reduce.html",
    title: "JavaScript Demo: Array.reduce()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-reverse.js",
    fileName: "array-reverse.html",
    title: "JavaScript Demo: Array.reverse()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-shift.js",
    fileName: "array-shift.html",
    title: "JavaScript Demo: Array.shift()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-slice.js",
    fileName: "array-slice.html",
    title: "JavaScript Demo: Array.slice()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-some.js",
    fileName: "array-some.html",
    title: "JavaScript Demo: Array.some()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-sort.js",
    fileName: "array-sort.html",
    title: "JavaScript Demo: Array.sort()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-splice.js",
    fileName: "array-splice.html",
    title: "JavaScript Demo: Array.splice()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-tolocalestring.js",
    fileName: "array-tolocalestring.html",
    title: "JavaScript Demo: Array.toLocaleString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-tostring.js",
    fileName: "array-tostring.html",
    title: "JavaScript Demo: Array.toString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-unshift.js",
    fileName: "array-unshift.html",
    title: "JavaScript Demo: Array.unshift()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/array/array-values.js",
    fileName: "array-values.html",
    title: "JavaScript Demo: Array.values()",
    type: "js",
  },
];
