export const dates = [
  {
    exampleCode: "../MDNExamples/js-examples/date/date-constructor.js",
    fileName: "date-constructor.html",
    title: "JavaScript Demo: Date Constructor",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getdate.js",
    fileName: "date-getdate.html",
    title: "JavaScript Demo: Date.getDate()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getday.js",
    fileName: "date-getday.html",
    title: "JavaScript Demo: Date.getDay()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getfullyear.js",
    fileName: "date-getfullyear.html",
    title: "JavaScript Demo: Date.getFullYear()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-gethours.js",
    fileName: "date-gethours.html",
    title: "JavaScript Demo: Date.getHours()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getmilliseconds.js",
    fileName: "date-getmilliseconds.html",
    title: "JavaScript Demo: Date.getMilliseconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getminutes.js",
    fileName: "date-getminutes.html",
    title: "JavaScript Demo: Date.getMinutes()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getmonth.js",
    fileName: "date-getmonth.html",
    title: "JavaScript Demo: Date.getMonth()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getseconds.js",
    fileName: "date-getseconds.html",
    title: "JavaScript Demo: Date.getSeconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-gettime.js",
    fileName: "date-gettime.html",
    title: "JavaScript Demo: Date.getTime()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-gettimezoneoffset.js",
    fileName: "date-gettimezoneoffset.html",
    title: "JavaScript Demo: Date.getTimezoneOffset()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcdate.js",
    fileName: "date-getutcdate.html",
    title: "JavaScript Demo: Date.getUTCDate()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcday.js",
    fileName: "date-getutcday.html",
    title: "JavaScript Demo: Date.getUTCDay()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcfullyear.js",
    fileName: "date-getutcfullyear.html",
    title: "JavaScript Demo: Date.getUTCFullYear()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutchours.js",
    fileName: "date-getutchours.html",
    title: "JavaScript Demo: Date.getUTCHours()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcmonth.js",
    fileName: "date-getutcmonth.html",
    title: "JavaScript Demo: Date.getUTCMonth()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcmilliseconds.js",
    fileName: "date-getutcmilliseconds.html",
    title: "JavaScript Demo: Date.getUTCMilliseconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcminutes.js",
    fileName: "date-getutcminutes.html",
    title: "JavaScript Demo: Date.getUTCMinutes()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-getutcseconds.js",
    fileName: "date-getutcseconds.html",
    title: "JavaScript Demo: Date.getUTCSeconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-now.js",
    fileName: "date-now.html",
    title: "JavaScript Demo: Date.now()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-parse.js",
    fileName: "date-parse.html",
    title: "JavaScript Demo: Date.parse()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setdate.js",
    fileName: "date-setdate.html",
    title: "JavaScript Demo: Date.setDate()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setfullyear.js",
    fileName: "date-setfullyear.html",
    title: "JavaScript Demo: Date.setFullYear()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-sethours.js",
    fileName: "date-sethours.html",
    title: "JavaScript Demo: Date.setHours()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setmilliseconds.js",
    fileName: "date-setmilliseconds.html",
    title: "JavaScript Demo: Date.setMilliseconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setminutes.js",
    fileName: "date-setminutes.html",
    title: "JavaScript Demo: Date.setMinutes()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setmonth.js",
    fileName: "date-setmonth.html",
    title: "JavaScript Demo: Date.setMonth()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setseconds.js",
    fileName: "date-setseconds.html",
    title: "JavaScript Demo: Date.setSeconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-settime.js",
    fileName: "date-settime.html",
    title: "JavaScript Demo: Date.setTime()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcdate.js",
    fileName: "date-setutcdate.html",
    title: "JavaScript Demo: Date.setUTCDate()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcfullyear.js",
    fileName: "date-setutcfullyear.html",
    title: "JavaScript Demo: Date.setUTCFullYear()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutchours.js",
    fileName: "date-setutchours.html",
    title: "JavaScript Demo: Date.setUTCHours()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcmilliseconds.js",
    fileName: "date-setutcmilliseconds.html",
    title: "JavaScript Demo: Date.setUTCMilliseconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcminutes.js",
    fileName: "date-setutcminutes.html",
    title: "JavaScript Demo: Date.setUTCMinutes()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcmonth.js",
    fileName: "date-setutcmonth.html",
    title: "JavaScript Demo: Date.setUTCMonth()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-setutcseconds.js",
    fileName: "date-setutcseconds.html",
    title: "JavaScript Demo: Date.setUTCSeconds()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-todatestring.js",
    fileName: "date-todatestring.html",
    title: "JavaScript Demo: Date.toDateString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-toisostring.js",
    fileName: "date-toisostring.html",
    title: "JavaScript Demo: Date.toISOString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-tojson.js",
    fileName: "date-tojson.html",
    title: "JavaScript Demo: Date.toJSON()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-tolocaledatestring.js",
    fileName: "date-tolocaledatestring.html",
    title: "JavaScript Demo: Date.toLocaleDateString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-tolocalestring.js",
    fileName: "date-tolocalestring.html",
    title: "JavaScript Demo: Date.toLocaleString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-tolocaletimestring.js",
    fileName: "date-tolocaletimestring.html",
    title: "JavaScript Demo: Date.toLocaleTimeString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-toprimitive.js",
    fileName: "date-toprimitive.html",
    title: "JavaScript Demo: Date.prototype[@@toPrimitive]",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-tostring.js",
    fileName: "date-tostring.html",
    title: "JavaScript Demo: Date.toString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-totimestring.js",
    fileName: "date-totimestring.html",
    title: "JavaScript Demo: Date.toTimeString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-toutcstring.js",
    fileName: "date-toutcstring.html",
    title: "JavaScript Demo: Date.toUTCString()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-utc.js",
    fileName: "date-utc.html",
    title: "JavaScript Demo: Date.UTC()",
    type: "js",
  },
  {
    exampleCode: "../MDNExamples/js-examples/date/date-valueof.js",
    fileName: "date-valueof.html",
    title: "JavaScript Demo: Date.valueOf()",
    type: "js",
  },
];
